syntax = "proto3";

package infracost.parser.messages;

import "infracost/parser/cloudformation/result.proto";
import "infracost/parser/cloudformation/target.proto";
import "infracost/parser/diagnostic.proto";
import "infracost/parser/terraform/module.proto";
import "infracost/parser/terraform/target.proto";
import "infracost/parser/terragrunt/target.proto";

// ParseRequest is the unified request for all parser types.
message ParseRequest {
  // The root path of the repository to be parsed
  string repo_directory = 1;
  // The working directory of the project in the repository being processed
  string working_dir = 2;
  // The Target type that is being parsed. Eg; cloudformation, terraform, terragrunt
  ParseRequestTarget target = 3;
}

// ParseRequestTarget is the unified target for all parser types.
message ParseRequestTarget {
  oneof value {
    // The target type for Terraform files
    terraform.Target terraform = 10;
    // The target type for Terragrunt files
    terragrunt.Target terragrunt = 11;
    // The target type for CloudFormation files
    cloudformation.Target cloudformation = 12;
  }
}

// ParseResponse is the unified response for all parser types.
message ParseResponse {
  // The diagnostics generated during parsing
  repeated Diagnostic diagnostics = 1;
  // The result of parsing the target, is one of cloudformation, terraform, terragrunt
  ParseResponseResult result = 2;
}

// ParseResponseResult is the unified result for all parser types.
message ParseResponseResult {
  oneof value {
    terraform.ModuleResult terraform = 10;
    terragrunt.Result terragrunt = 11;
    cloudformation.Result cloudformation = 12;
  }
}
