syntax = "proto3";

package infracost.provider;

import "infracost/parser/event/runparameters.proto";
import "infracost/parser/messages/message.proto";
import "infracost/provider/usage.proto";

message Input {
  // The output of a parser, such as a Terraform module result, or a CloudFormation result
  infracost.parser.messages.ParseResponse parse_result = 1;

  // Absolute path of the project/template being scanned
  // For Terraform/Terragrunt this will be a directory, for CFN this will be a template file
  string absolute_path = 2; // path to project

  // Specifies customer-defined (and default) usage data
  // This comes from zero or more of the cloud db, and/or a customer's committed usage file
  ProjectInfo project_info = 3;

  // Resource IDs that have been seen on a previous run (if relevant), which helps us figure
  // out if a resource is to be considered "new" or not.
  // This is mainly so we can ignore policies that only want to so consider "new" resources
  repeated string previous_resource_ids = 4;

  // TODO: comment!
  infracost.provider.Usage usage = 5;

  // Specifies which policies need to be run, and any custom settings for each.
  PolicyConfiguration policy_config = 6;

  // NOTE: this space is reserved for guard rails configuration
  reserved 7;

  // Features
  Features features = 8;

  Settings settings = 9;

  Infracost infracost = 10;
}

message Settings {
  string currency = 1;
  bool use_disk_caches = 2;
}

message Infracost {
  string api_key = 1;
  string pricing_api_endpoint = 2;
  string trace_id = 3;
}

message Features {
  bool enable_price_lookups = 1;
  bool enable_recommendations = 2;
  bool enable_finops_policies = 3;
  bool enable_tagging_policies = 4;
  bool enable_environmental_metrics = 5;
}

// Extra information about the project (formerly known as Scope in the runner)
message ProjectInfo {
  // Project name as it apepars in the config file
  string name = 1;
  // Git branch name being scanned, if applicable
  string branch_name = 2;
  // Workspace name (currently only used for Terraform workspace)
  string workspace = 3;
  // If the environment being scanned is production (only relevant for ICP)
  bool is_production = 4;
}

message PolicyConfiguration {
  // FinOps policy configuration (note: security policies are currently a subset of finops policies)
  FinOpsPolicyConfiguration finops = 1;
  // Tagging policy configuration
  TaggingPolicyConfiguration tagging = 2;
}

message FinOpsPolicyConfiguration {
  // If none are supplied, all available (default) policies should be run.
  repeated infracost.parser.event.FinopsPolicySettings policies = 1;
}

message TaggingPolicyConfiguration {
  // If none are supplied, all available (default) policies should be run.
  repeated infracost.parser.event.TagPolicy policies = 1;
}
