syntax = "proto3";

package infracost.provider;

import "infracost/parser/stack.proto";
import "infracost/rational/rational.proto";

message Output {
  // Normalised list of resources, made IaC-agnostic.
  repeated Resource resources = 1;
  // Details of passes/failures for each configured finops policy
  repeated FinopsPolicyResult finops_results = 2;
}

message Resource {
  // Unique resource id - this is supplied by the relevant parser
  string id = 1;
  // The resource type as supplied by the parser e.g. aws_instance or AWS::EC2::Instance
  string type = 2; // tf or cfn resource type
  // a unique resource name, usually populated with the full address of the resource
  string name = 3;
  // region if applicable, e.g. eu-west2
  string region = 4;
  // filename, line numbers, checksums
  ResourceMetadata metadata = 5;
  // string describing where the provider is defined for this resource
  string provider_link = 6;
  // If explicitly supported by Infracost
  bool is_supported = 7;
  // If the resource has no associated costs
  bool is_free = 8;
  // If the provider of the resource is supported
  bool is_provider_supported = 9;
  // if the resource was added for this run (if known)
  bool is_new = 10;
  // The resource costs - totals and individual cost components - including environmental metrics
  ResourceCosts costs = 11;
  // Resource-level tags
  Tagging tagging = 12;
  // Child resources e.g. a disk belonging to a VM, defined as part of a greater resource
  repeated Resource child_resources = 13;
  // the stack trace for this resource - e.g. module.X -> module.X.module.Y -> module.X.module.Y.resource.Z
  parser.CallStack call_stack = 14;
}

message ResourceMetadata {
  // the path to the file (relative to the repository) where the resource is defined
  string filename = 1;
  // line numbers where the resource is defined
  int64 start_line = 2;
  int64 end_line = 3;
  // module calls leading to this resource (e.g. module.a -> module.b -> resource.c)
  repeated ModuleCall module_calls = 4;
  // basic checksum identifying the unique resource (address etc.), not its children or contents
  string basic_checksum = 5;
  // deep checksum identifying the resource including its children and contents
  string deep_checksum = 6;
  // checksum of default tag values applied to this resource
  string default_tags_checksum = 7;
}

message ModuleCall {
  // the name of the thing that defined this module, e.g. "module.x" in terraform
  string definition_name = 1; // i.e. block name
  // filename where this module was called
  string filename = 2;
  // line numbers where this module was called
  int64 start_line = 3;
  int64 end_line = 4;
}

message Tagging {
  // tag values
  repeated Tag tags = 1;
  // if this resource supports tags at all
  bool supports_tags = 2;
  // If the provider supports default tags here (so we can differentiate between this and there being no defaults)
  bool supports_default_tags = 3;
  // Propagation data. This tells us if the tags are propagated from one resource to another, and whether this is configured properly.
  repeated TagPropagationProblem propagation_problems = 4;
}

message Tag {
  // tag key (name)
  string key = 1;
  // tag value
  string value = 2;
  // whether this is a default tag
  bool is_default = 3;
  // whether the key was synthetically generated (e.g. we made up a value because the real one was not defined)
  bool is_key_synthetic = 4;
  // whether the value was synthetically generated (e.g. we made up a value because the real one was not defined)
  bool is_value_synthetic = 5;
}

message TagPropagationProblem {
  // actual discovered value for the attribute (formerly known as "From" for some reason)
  string actual_value = 1;
  // valid values for the attribute which would enable propagation (formerly known as "ValidSources")
  repeated string valid_values = 2;
  // the attribute which dictates whether propagation is enabled
  string attribute = 3;
  // a noun describing the recipient of the tags if propagation is enabled (formerly known as "To")
  string tag_recipient = 4;
  // tag keys which are affected by this propagation problem
  repeated string affected_tags = 5;
}

message ResourceCosts {
  // a list of cost line items directly associated with this resource
  repeated CostComponent components = 1;
}

message CostComponent {
  // Display name for cost component, but also contains some attributes e.g. Compute (t3.small, on-demand)
  string name = 1;
  // The `quantity` refers to the number of these `unit`s, and the `period_price` is for each of these. e.g. if `unit` is "cores", the `period_price` is per core, and the `quantity` is the number of cores.
  string unit = 2;
  // Whether the `period_price` is based on usage data
  bool usage_based = 3;
  // Whether we found a `period_price` for this (_false_ if a custom price was used)
  bool price_not_found = 4;
  // Whether the price was hardcoded in the provider plugin, or in the usage data
  bool price_was_hardcoded = 5;
  // The price, pre-discount, of each `unit` (per price period)
  PeriodPrice period_price = 6;
  // This is the number we need to multiply `period_price` by to arrive at a pre-discounted cost
  infracost.rational.Rat quantity = 7;
  // The rate to multiply the `period_price` by to calculate savings. i.e. discounted_cost = cost - (cost * discount_rate)
  infracost.rational.Rat discount_rate = 8;
  // Information on how fast your infrastructure is destroying the planet
  EnvironmentalMetrics environmental_metrics = 9;
}

message PeriodPrice {
  // the raw price as a rational number
  infracost.rational.Rat price = 1;
  // this is the period to which the price applies (i.e. monthly or hourly)
  Period period = 2;
}

enum Period {
  MONTH = 0;
  HOUR = 1;
}

message EnvironmentalMetrics {
  // the period to which the metrics apply (i.e. monthly or hourly)
  Period period = 1;
  // carbon emissions in grams CO2e
  infracost.rational.Rat carbon_grams_co2e = 2;
  // water usage in liters
  infracost.rational.Rat water_liters = 3;
}

message FinopsPolicyResult {
  // Unique policy ID (UUID v4, from dashboard API)
  string policy_id = 1;
  // Human-readable policy name
  string policy_name = 2;
  // Human-readable policy slug, used to identify specific policy code in provider plugins
  string policy_slug = 3;
  // Message describing the policy result
  string policy_message = 4;
  // Resource IDs that passed this policy
  repeated string passing_resource_ids = 5;
  // Resources that failed this policy, along with details of the individual issues
  repeated FinopsPolicyFailingResource failing_resources = 6;
  // should this failure cause the pull request to be blocked (if PR blocking is enabled at a higher level)
  bool block_pull_request = 7;
  // should this policy result be included in the pull request comment
  bool include_in_pull_request_comment = 8;
  // does this policy only apply to new resources
  bool only_applies_to_new_resources = 9;
}

message FinopsPolicyFailingResource {
  // Unique resource ID (can be matched against the Resource.id field to identify a full resource)
  string id = 1;
  // the full address to the cause of the failure
  string cause_address = 2;
  // Details of the individual issues for this resource
  repeated FinopsResourceIssue issues = 3;
}

message FinopsResourceIssue {
  // monthly financial savings (in configured currency) that could be realized by fixing this issue
  infracost.rational.Rat monthly_savings = 1;
  // monthly carbon savings in grams CO2e that could be realized by fixing this issue
  infracost.rational.Rat monthly_carbon_savings_grams_co2e = 2;
  // monthly water savings in litres that could be realized by fixing this issue
  infracost.rational.Rat monthly_water_savings_litres = 3;
  // human-readable address where the issue originates
  string address = 4;
  // attribute of the resource where the issue originates
  string attribute = 5;
  // detailed description of the issue
  string description = 6;
  // extra details pertaining to the financial savings
  optional string savings_details = 7;
  // breakdowns of costs before and after fixing the issue
  repeated IssueBreakdown before_fix_breakdowns = 8;
  repeated IssueBreakdown after_fix_breakdowns = 9;
}

message IssueBreakdown {
  // name of the resource or subresource
  string resource_name = 1;
  // region of the resource or subresource
  string region = 2;
  // cost components for this resource or subresource
  repeated IssueCostComponent cost_components = 3;
  // nested subresources
  repeated IssueBreakdown subresources = 4;
}

message IssueCostComponent {
  // name of the cost component e.g. "compute cost"
  string name = 1;
  // unit the cost is measured in e.g. "hours", "GB", "vCPU/seconds"
  string unit = 2;
  // Whether the `period_price` is based on usage data
  bool usage_based = 3;
  // The price, pre-discount, of each `unit` (per price period)
  PeriodPrice period_price = 4;
  // This is the number we need to multiply `period_price` by to arrive at a pre-discounted cost
  infracost.rational.Rat quantity = 5;
  // The rate to multiply the `period_price` by to calculate savings. i.e. discounted_cost = cost - (cost * discount_rate)
  infracost.rational.Rat discount_rate = 6;
}

message InvalidTag {
  // tag key (name)
  string key = 1;
  // tag value
  string value = 2;
  // message describing why the tag is invalid
  string message = 3;
  // valid values for the tag
  repeated string valid_values = 4;
  // whether the valid values list was truncated (sometimes there are ~100k!)
  bool valid_values_truncated = 5;
  // whether this tag came from default tags
  bool from_default_tags = 6;
  // whether this tag is missing but mandatory
  bool missing_mandatory = 7;
  // when the value must match a regex, the regex pattern
  optional string valid_regex = 8;
  // suggestion for a valid value, so we can suggest "did you mean 'Production', not 'prdcutoin'?"
  optional string suggestion = 9;
}
