syntax = "proto3";

package infracost.provider;

import "infracost/provider/rational.proto";
import "infracost/provider/usage.proto";

// TODO: add comment above each field

message Output {
    // Normalised list of resources, made IaC-agnostic.
    repeated Resource resources = 1;
    // Details of passes/failures for each configured finops policy
    FinopsPolicyResults finops = 2;
    // Details of passes/failures for each configured tagging policy
    TaggingPolicyResults tagging = 3;
    // Details of passes/failures for each configured guardrail
    GuardRailsResults guard_rails_results = 4;
}

message Resource {
    // Unique resource id - this is supplied by the relevant parser
    string id = 1;
    // TODO: need to figure out if we need this...
    Metadata metadata = 2; // ???
    // The resource type as supplied by the parser e.g. aws_instance or AWS::EC2::Instance
    string resource_type = 3; // tf or cfn resource type
    // TODO: ???
    string provider_link = 4;
    // TODO: ???
    string skip_message = 5;
    // TODO: resource name - usually the address of the resource?
    string name = 6;
    // If explicitly supported by Infracost
    bool is_supported = 7;
    // If the resource has no associated costs
	bool is_free = 8;
	// If the provider of the resource is supported
	bool is_provider_supported = 9;
	// The resource costs - totals and individual cost components - including environmental metrics
    ResourceCosts costs = 10;
    // Child resources e.g. a disk belonging to a VM, defined as part of a greater resource
	repeated Resource child_resources = 11;

}

message Tags {
    // Default tags
    repeated Tag default_tags = 1;
    // Resource-level tags
    // TODO: do these include default values?
    repeated Tag tags = 2;
    // If the provider supports default tags here (so we can differentiate between this and there being no defaults)
    bool default_tags_supported = 3;
    // List of missing (undefined) variables that result in us not knowing all tag keys
    // We use this so we can avoid report missing tags if we're unsure if the tags are really missing, as one or more tags exists with an unknown key.
    repeated string missing_vars_causing_unknown_tag_keys = 4;
    // List of missing (undefined) variables that result in us not knowing all default tag keys
    repeated string missing_vars_causing_unknown_default_tag_keys = 5;
    // Propagation data. This tells us if if the tags are propagated from one resource to another, and whether this is configured properly.
    TagPropagation propagation = 6;
}

message TagPropagation {
    // TODO: !!!
    To                    string             `json:"to"`
	From                  *string            `json:"from,omitempty"`
	Tags                  *map[string]string `json:"tags,omitempty"`
	Attribute             string             `json:"attribute"`
	HasRequiredAttributes bool               `json:"hasRequiredAttributes,omitempty"`
}

message ResourceCosts {
    // Total hourly cost of the resource
    // TODO: can we remove this and calc from monthly?
    infracost.provider.Rat hourly_base = 1;
    // Total monthly cost of the resource
    infracost.provider.Rat monthly_base = 2;
    infracost.provider.Rat monthly_usage = 3;
    EnvironmentalMetrics environmental_metrics = 4;
    repeated CostComponent components = 5;
}

message CostComponent {
  // Display name for cost component, but also contains some attributes e.g. Compute (t3.small, on-demand)
  string name = 1;
  // The `quantity` refers to the number of these, and the `period_price` is for each of these. e.g. if `unit` is "cores", the `period_price` is per core, and the `quantity` is the number of cores.
  string unit = 2;
  // Whether the `period_price` is based on usage data
  bool usage_based = 3;
  // Whether we found a `period_price` for this (_false_ if a custom price was used)
  bool price_not_found = 4;
  // Whether the price was hardcoded in the provider plugin, or in the usage data
  bool price_was_hardcoded = 5;
  // The price, pre-discount, of each `unit` (per price period)
  PeriodPrice period_price = 6;
  // This is the number we need to multiple `period_price` by to arrive at a pre-discounted cost
  infracost.provider.Rat quantity = 7;
  // The factor to multiply the `period_price` by to arrive at a discounted price (currently only used for Google Compute sustained use discounts)
  infracost.provider.Rat discount_factor = 8;
  // Information on how fast your infrastructure is destroying the planet
  EnvironmentalMetrics environmental_metrics = 9;
}

message PeriodPrice {
   infracost.provider.Rat price = 7;
   Period period = 6;
}

enum Period {
  MONTH = 0;
  HOUR = 1;
}

message ResourceEnvironmentalMetrics {
    PricePerPeriod carbon_grams_co2e = 1;
    PricePerPeriod water_liters = 2;
}

message Tag {
    string key = 1;
    string value = 2;
}

message FinopsPolicyResults {
  string policy_id = 1;
  string policy_name = 2;
  string policy_slug = 3;
  string policy_message = 4;
  repeated string applicable_resources = 5; // addresses of all applicable resources
  repeated FinopsPassingResource passing_resources = 6;
  repeated FinopsFailingResource failing_resources = 7;
  bool block_pull_request = 8;
  bool include_in_pull_request_comment = 9;
  bool only_applies_to_new_resources = 10;
}

message FinopsPassingResource {
    // TODO: !!!
}


message FinopsFailingResource {
    // TODO: !!!
}

message TaggingPolicyResults {
 // TODO: !!!
}

message GuardRailsResults {
    // placeholder
}
