syntax = "proto3";

package infracost.provider;

import "infracost/provider/input.proto";
import "infracost/provider/output.proto";

service ProviderService {
  rpc Process(ProcessRequest) returns (ProcessResponse);
  rpc ListFinopsPolicies(ListFinopsPoliciesRequest) returns (ListFinopsPoliciesResponse);
}

message ProcessRequest {
  Input input = 1;
}

message ProcessResponse {
  Output output = 2;
}

message ListFinopsPoliciesRequest {}

message ListFinopsPoliciesResponse {
  repeated FinopsPolicy policies = 1;
}

message FinopsPolicy {
  string slug = 1;
  string name = 2;
  string group = 3;
  string description = 4;
  bool only_new_resources = 5;
}
