syntax = "proto3";

package infracost.parser.terraform;

import "infracost/parser/hcl/value.proto";
import "infracost/parser/terraform/modules/loader.proto";

message Target {
  string directory = 1;
  modules.LoadedModule loaded_module = 2;
  Options options = 3;
}

/*
   type Config struct {
   	Logger                             logger.Logger - nope
   	DebugTarget                        *debug.Target - YES
   	CredsSource                        *modules.CredentialsSource
   	SourceMap                          map[string]string
   	Env                                map[string]string
   	Vars                               map[string]state.Value
   	DefaultTags                        map[state.Value]state.Value
   	GenerationMappings                 map[string]*metadata.SourceRange - NOPE
   	EnvironmentName                    string
   	ProjectName                        string
   	TemporaryDirectory                 string
   	OriginalDirectory                  string - maybe not needed
   	Workspace                          string
   	TfvarsFiles                        []string
   	hooks                              []func(*ModuleInstance)
   	TFCConfigurations                  []TFCConfiguration
   	RemoteVariableLoaders              []RemoteVariableLoader
   	MaxConcurrentBlocksPerModuleAtRoot int
   	BaseFlags                          uint64
   	resourceSupportFunc                func(string) bool // nope list of supported resources provided by the caller
   	ForceLocalModulePaths              bool
   	DependencyPathsTracker             *dependencies.DependencyPathsTracker - not required
   }*/

message Debug {
  string address = 1;
  bool include_dumps = 2;
}

message CredentialSet {
  string token = 1;
  string host = 2;
}

message Options {
  // Module address to include debug in the output for. include dumps to extend debug information provided
  Debug debug = 1;
  // The credential set to use for authentication, provided as a tu
  repeated CredentialSet credential_sets = 2;
  // Map of module addresses to source paths TODO: Is this correct ????????????????
  map<string, string> source_map = 3;
  // Map of module addresses to regex source paths TODO: Is this correct ????????????????
  map<string, string> regex_source_map = 4;
  // Map of environment variables to their values
  map<string, string> env = 5;
  // Map of variables to their values
  map<string, infracost.parser.hcl.Value> vars = 6;
  // Map of default tags to their values
  map<string, infracost.parser.hcl.Value> default_tags = 7;
  // The environment name to use for the output
  string environment_name = 8;
  // The project name to use for the output
  string project_name = 9;
  // The temporary directory that is being worked in
  string temporary_directory = 10;
  // The workspace for the project - TODO is this the Terraform workspace?
  string workspace = 11;
  // A list of Terraform Var files
  repeated string tf_vars_files = 12;
  int32 max_concurrent_blocks_per_module_at_root = 13;
  uint64 base_flags = 14;
  bool force_local_module_paths = 15;
}
